name: Build IMDER

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: IMDER_windows
            executable: IMDER.exe
          - os: ubuntu-latest
            artifact_name: IMDER_linux
            executable: IMDER
          - os: macos-latest
            artifact_name: IMDER_macOS
            executable: IMDER

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5 opencv-python numpy pillow pyinstaller

    - name: Build on Windows
      if: runner.os == 'Windows'
      run: |
        pyinstaller --noconfirm --onefile --windowed `
          --icon "src/imder.ico" `
          --hide-console "hide-early" `
          --add-data "src/imder.png;." `
          "src/imder.py"

    - name: Build on Linux
      if: runner.os == 'Linux'
      run: |
        pyinstaller --noconfirm --onefile --windowed \
          --icon "src/imder.ico" \
          --add-data "src/imder.png:." \
          "src/imder.py"

    - name: Build on macOS
      if: runner.os == 'macOS'
      run: |
        pip install pyobjc
        pyinstaller --noconfirm --onefile --windowed \
          --icon "src/imder.ico" \
          --add-data "src/imder.png:." \
          "src/imder.py"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.executable }}
